---
name: Build
on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 's3gw-core'

      - name: Checkout Ceph
        uses: actions/checkout@v3
        with:
          repository: 'aquarist-labs/ceph'
          ref: 's3gw'
          path: 'ceph'
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Build Buildenv Container
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: localhost:5000/local/radosgw-builder:latest
          file: 's3gw-core/build/Dockerfile.build-radosgw'
          context: 's3gw-core/build'

      - name: Build radosgw Binary
        run: |
          docker run --rm \
            -v $GITHUB_WORKSPACE/ceph:/srv/ceph \
            -e NPROC=4 \
            localhost:5000/local/radosgw-builder:latest
          ls -la $GITHUB_WORKSPACE/ceph/build/bin
